# fly.toml app configuration file generated for datasetexplorer on 2024-03-14T02:56:37-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'datasetexplorer'
primary_region = 'mia'

[build]
  image = 'theail03/datasetexplorer:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dj3wmuy3l"
  CloudinarySettings__ApiKey="895484589483755"
  RunMigrations="false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
